// Mapa de ingredientes a emojis para mostrar en botones de filtro
const map: Record<string, string> = {
  "Arroz": "🍚",
  "Arroz cocido": "🍚",
  "Presas de pollo": "🍗",
  "Pollo entero": "🍗",
  "Pechuga de pollo": "🍗",
  "Cebolla": "🧅",
  "Cebolla morada": "🧅",
  "Cebollín": "🌱",
  "Pimentón": "🫑",
  "Pimentón en polvo": "🌶️",
  "Zanahoria": "🥕",
  "Ajo": "🧄",
  "Aceite": "🫒",
  "Aceite de oliva": "🫒",
  "Aceite de sésamo": "🫒",
  "Sal": "🧂",
  "Comino": "🌿",
  "Pasta": "🍝",
  "Carne molida": "🥩",
  "Carne de vacuno": "🥩",
  "Tomate": "🍅",
  "Tomate triturado": "🍅",
  "Orégano": "🌿",
  "Tortillas de maíz": "🫓",
  "Tortillas de harina": "🫓",
  "Cilantro": "🌿",
  "Limón": "🍋",
  "Palta": "🥑",
  "Ají rojo": "🌶️",
  "Ají": "🌶️",
  "Lechuga": "🥬",
  "Lechuga romana": "🥬",
  "Pan para crutones": "🍞",
  "Pan de hamburguesa": "🍞",
  "Pan rallado": "🍞",
  "Queso parmesano": "🧀",
  "Queso": "🧀",
  "Queso Oaxaca": "🧀",
  "Queso rallado": "🧀",
  "Queso mozzarella": "🧀",
  "Aderezo César": "🥗",
  "Lentejas": "🫘",
  "Papa": "🥔",
  "Pimienta": "🌶️",
  "Champiñones": "🍄",
  "Filete de pescado": "🐟",
  "Perejil": "🌿",
  "Huevos": "🥚",
  "Huevo duro": "🥚",
  "Arvejas": "🟢",
  "Salsa de soya": "🍶",
  "Choclo (maíz tierno)": "🌽",
  "Mazorca de maíz": "🌽",
  "Albahaca": "🌿",
  "Mantequilla": "🧈",
  "Aceitunas negras": "🫒",
  "Pasas": "🍇",
  "Azúcar": "🍬",
  "Harina": "🌾",
  "Harina de maíz precocida": "🌾",
  "Manteca": "🧈",
  "Zapallo": "🎃",
  "Yuca": "🥔",
  "Plátano verde": "🍌",
  "Romero": "🌿",
  "Agua tibia": "💧",
  "Camote": "🍠",
  "Láminas de lasaña": "🍝",
  "Leche": "🥛",
  "Crema": "🥛",
  "Crema ácida": "🥛",
  "Porotos rojos": "🫘",
  "Leche de coco": "🥥",
  "Jengibre": "🫚",
  "Curry en polvo": "🌶️",
  "Vino tinto": "🍷",
  "Fideos": "🍜",
};

export const getIngredientEmoji = (name: string): string => map[name] ?? "🍽️";
